on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
          cache: npm
      - name: Execute npm test
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          ORGANIZATION: ${{ vars.ORGANIZATION }}
        run: |
          npm ci
          tsc
          npm test
